### ISSUE TITLE
[Android Bootcamp] Project 0: Simple Todo - Ready for review

### ISSUE THREAD

**Issue by neerajakshid** [neerajakshid/SimpleTodo#1]
My SimpleTodo app is complete, please review. /cc @codepathreview @codepath

**Comment by neerajakshid** [comment]
I have added the following additional features to the SimpleTodo app and updated the code in github:
- I have updated the functionality to store list items to an SQLiteDatabase using SQLiteOpenHelper class
- I have added support for selecting the priority of each item and displayed the priority on the list.
- I have used a custom adapter for improving the style of the list items. 

Will start working on adding completion due dates and sorting the list based on the due dates and DialogFragment for editing items. 

Please review @codepathreview @codepath

**Comment by neerajakshid** [comment]
I have added the following additional features to the SimpleTodo app and updated the code in github:
- I have added support for completion due dated using DatePicker.
- Used DialogFragment for adding/editing items.

Will start working on improving UI/UX.

Please review @codepathreview @codepath

**Comment by nesquena** [comment]
Neerajakshi,

Looks good! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 5-10 minute phone conversation** [here](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc). Navigate to [today's date and onward from there](https://www.google.com/calendar/selfsched?sstoken=UU5IOEduOWEtRDg5fGRlZmF1bHR8NWRiNTI5ZWJmMjVjODg1OGVhMmU0NDg5Nzc2NDRlNTc) and choose a 15-minute slot. Let us know if none of those times work.

Once you select a slot, can you make sure to **include best number** to reach you at? Look forward to chatting soon!

**Comment by neerajakshid** [comment]
Thanks!! I have booked an appointment for tomorrow.

**Comment by neerajakshid** [comment]
I have added the following additional features to the SimpleTodo app and updated the code in github:
- Optional: Added an image for adding new items (using ImageButton) instead of a button
- Optional: A scheduled notification to the user with the list of items based on the due date
  - Notification will be generated on running the code from Android Studio
  - Then the notification is scheduled to trigger every 24 hours (using AlarmManager) even though the app is not in use
  - Notification will not be trigerred when there are no action items for that day

Please review @codepathreview @codepath

**Comment by neerajakshid** [comment]
I have changed the background color of the main activity and moved the add icon to the action bar as an improvement to the UX of the app. I have pushed the updated code to github.

Please review @codepathreview @codepath

**Comment by nidhi1608** [comment]
Nice, looks good. Glad you're already thinking about improving the UI/ UX of the app.
